### ISSUE TITLE
ack for Pub and Sub / delete message after successful delivery

### ISSUE THREAD

**Issue by steventanwc** [nats-io/go-nats-streaming#101]
Hi experts,

I have successfully run the Nats-Streaming Go clients to publish and subscribe and consume the message from a nats-streaming server.

Would appreciate if someone can help me on how I pub and sub with ack and the ack results can be called back in the client.

Another related question: If the message is delivered to subscriber successfully with an acr, will Nats Streaming Server automatically delete the message from the store? If no, how can we implement that? I know there is a max message in store for each channel, but the delivered messages will take up unnecessary storage.

Thank u in advance

Steven Tan

ps: sorry I accidentally posted the message in nats

**Comment by aricart** [comment]
Hi Steven,

Glad you are trying the nats-streaming-server.

I am not quite sure what you mean by:
> Would appreciate if someone can help me on how I pub and sub with ack and the ack results can be called back in the client.

If you want to handle acks manually you have to set an option when creating the subscription (see the `SetManualAckMode()`). If you do this, you'll have to manually use `Msg.Ack()` to acknowledge messages you receive.

> Another related question: If the message is delivered to subscriber successfully with an acr, will Nats Streaming Server automatically delete the message from the store? If no, how can we implement that? I know there is a max message in store for each channel, but the delivered messages will take up unnecessary storage.

Actually when you start up the nats-streaming-server there are two options:

`-max_msgs <number>` and `-max_bytes <number>` that you can specify. These control how many messages (or how much data) for a channel the server will keep track of. Effectively, if you have `-max_msgs 3`, the server will keep track of the last 3 messages sent. Each additional message sent to the streaming server will discard the oldest one received. Similarly if you specify `-max_bytes` the server will discard messages in order to keep the specified footprint.

Hope this helps!

**Comment by kozlovic** [comment]
@steventanwc , for the pub ack, this is relevant only if you are using the async publish calls `PublishAsync` and/or `PublishAsyncWithReply`. In this case, you can provide a callback which will be invoked when the library receives the confirmation from the server that the message was persisted, or a timeout error. Otherwise, the other publish calls will wait in place that the confirmation is received from the server (some languages may have different behavior, think node.js for instance).

For the subscriber, as @aricart mentioned, you would need to use manual ack mode if you want to be responsible for acknowledging the message. The default is auto-ack, which means that the library sends the ack for you.

As for removing messages from the store, NATS Streaming is not your traditional messaging where messages are stored only based on an interest, and therefore can be removed when all consumers have acknowledged the messages or interest disappear. Streaming is a message log based approach where produced messages are logged and consumers can start after the fact and "replay" messages at any point in the stream (index or time based). Therefore, the server cannot and will not remove messages since messages are not attached to consumers. The server will remove old messages only based on the limit set per channel, but this is not what you were looking for.

Note that the server maintains the state of the consumers in other files. Those files track which consumers have receive which messages and which ones have been acknowledged. These files will be compacted as needed.

Hope this clarifies how NATS Streaming is working.

**Comment by steventanwc** [comment]
Hi guys

Thank u for your prompt response. 

I have managed to get the following running:

Pub with ack
Sub with durable

So when I restart server or client, the message is persisted and client only retrieve from the last sub-ack.

This satisfy the flow for chat perfectly

Thank u so much. 

Next phase I need to implement the client to connect to nats streaming server.

I am using ionic (html5) for frontend

Can u give me some suggestions on how I can create js version of nats streaming client. 

I am really new to go. I started on go because of nats streaming server as I see huge potential in what u guys have done. 

Can I use gopherJS to convert go to js? If yes, which are the files I need to convert?

I see that there is a nats.js in the nats node client

Is that something I need too?

Sorry to ask u many questions as I am very excited to embark on this. 

Thank u

Steven Tan

**Comment by kozlovic** [comment]
@Steven No worries! Questions and feedback are welcomed. Glad that you are finding the project interesting and that it is meeting your needs.
As for the client, good news: we are planning to release a node.js Streaming client. @aricart is in charge of that. Stay tuned!

**Comment by aricart** [comment]
@steventanwc Great that it is working for you. I am currently working on the node-nats-streaming client, however this is still under development. The api is geared towards nodejs, but you may be able to use [bowserify](http://browserify.org/) to get around some of the dependencies. Stay tuned!

**Comment by steventanwc** [comment]
Thank u so much. 

Looking forward to the node client.

Any rough timeline when. The client will be released?

**Comment by aricart** [comment]
Working on the unit tests :)




On July 26, 2016 at 6:53:36 PM, steventanwc (notifications@github.com)
wrote:

Thank u so much.

Looking forward to the node client.

Any rough timeline when. The client will be released?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/nats-io/go-nats-streaming/issues/101#issuecomment-235441478>,
or mute the thread
