### ISSUE TITLE
Will this client get merged into nats-io/nats at some point?

### ISSUE THREAD

**Issue by arekkas** [nats-io/go-nats-streaming#108]
Is the separation of nats-streaming-server / gnatsd and the client libraries only temporary or will it persist in the future as well?

**Comment by kozlovic** [comment]
NATS Streaming is a different project than NATS, so separation is permanent.

Thanks!

**Comment by arekkas** [comment]
So what would happen if I create a message architecture now and I want to add streaming later on, because I realise that I need it due to some reason. This would imply that I need to publish messages twice (one for streaming, one for normal nats) and thus change more code. I don't think this is ideal.

**Comment by kozlovic** [comment]
It was clear since the beginning of the project that we wanted to keep NATS "core" untouched. NATS strong points is the simplicity and performance. We did not want to add any code that would affect performance if not required for the core functionality. There are many users out there that love NATS for that and don't need persistence.
When we decided to provide persistence, it was then decided to have a different server/client that use NATS underneath. See this as a layer on top of NATS but without compromising NATS. The consequence was that, yes, it would be a different set of APIs. They are semantically very close though. Note that we have remove the original Req/Reply API from streaming, so they are a bit less alike now ;-)
To your comments: I understand the part of a rewrite, but not so much the part of needing to publish the message twice. If you need streaming and not regular NATS, then you would replace with streaming API but message is published once.

**Comment by arekkas** [comment]
> If you need streaming and not regular NATS, then you would replace with streaming API but message is published once.

That really depends on the type of publishers and consumers. Since pub/sub is n:m (n publishers, m consumers) m-1 could be a consumer requiring streaming whilst m-2 would not. In this case, I would have to add nats-streaming to every publisher and keep the original code as well. Does this make sense?

**Comment by arekkas** [comment]
Instead, it would be much easier to tell m-1 on an API level that we now need streaming and not mess with any publisher at all.

**Comment by arekkas** [comment]
A constructed use case would be a billing service, that publishes `billing.processed` and is initially consumed by an metrics service, that doesn't need delivery guarantee. At some point you need to add invoicing, which requires delivery guarantee because we must create invoices. So now you have both types of consumers, one which doesn't care if messages go lost and one that doesn't.

**Comment by arekkas** [comment]
I don't think that you need to merge nats-streaming into nats, but rather nats into nats-streaming. So people who add streaming on top can simply switch out the docker image, keep all the old APIs and have some consumers care about sequences.

**Comment by kozlovic** [comment]
Yes, that makes sense. But a bit of clarification. At the API level, even in NATS, the publisher does not assume the audience. In other words, it does not know if there are subscribers or not, simply sends a message. The server will drop that message if there is no interest, or will distribute to interested subscribers. So `Publish` to N with N being the number of intended subscribers is not a concept that fits with NATS.

**Comment by arekkas** [comment]
> Yes, that makes sense. But a bit of clarification. At the API level, even in NATS, the publisher does not assume the audience. In other words, it does not know if there are subscribers or not, simply sends a message. The server will drop that message if there is no interest, or will distribute to interested subscribers. So Publish to N with N being the number of intended subscribers is not a concept that fits with NATS.

This basically sums up what I am trying to say. Publishers should not care if the receivers want streaming or not. I don't feel that this is the case right now.

**Comment by kozlovic** [comment]
NATS Streaming server can embed NATS so you don't need a separate NATS server to run.
As for the NATS Streaming client, it also uses a NATS connection internally, which is accessible to the user with `Conn.NatsConn()`, from which you can make direct NATS API calls.
