### ISSUE TITLE
Send response on message

### ISSUE THREAD

**Issue by tisov** [nats-io/go-nats-streaming#121]
Hello
in [https://github.com/nats-io/go-nats](https://github.com/nats-io/go-nats) 
I can send a response to client after receive a message and get this data 
```go
var response string
err := c.Request("help", "help me", &response, 10*time.Millisecond) ...
```
How i can send to client a response here and get a data on the client side? I can't find. 
Thank you

**Comment by kozlovic** [comment]
In NATS, `Request()` uses a ephemeral inbox for the reply. That would not sit well at all with streaming since it would exhaust the number of channels very quickly. Also, in streaming, the "request" would be persisted, as the response. This does not make too much sense.

If your application needs both streaming and request/reply, we recommend that you do the request/reply through NATS and not streaming. You can have a dedicated NATS connection, or, if not convenient, the streaming API gives you access to the internal NATS connection that it uses: `conn.NatsConn()`. From there, you can call `Request()`.
