### ISSUE TITLE
Why no Request/Reply feature

### ISSUE THREAD

**Issue by thetooth** [nats-io/go-nats-streaming#128]
Normal NATS implements request that automatically creates a inbox for a reply and blocks until a server responds. I might be completely off here as I just see NATS streaming as a message bus+persistence. Is there a fundamental reason this neat feature is missing? It would be very handy in my use case(HTTP request uploads a video file, it's pushed into NATS where a number of workers will asynchronously pick up segments of the file and start processing at different points, thus allowing distributed processing of many very very large files).

This is more of a question of why would I not want to do this? If it's just a incomplete feature I can port it and provide a PR.

**Comment by kozlovic** [comment]
@thetooth NATS Streaming is a log based system. Messages that are published to a channel stay (*) in that channel regardless of subscribers presence or if messages are consumed/acknowledged.

When you do a request/reply, the requestor has the guarantee that the subscriber received and processed the message if it gets a reply back. If no reply, it can either try to resend or give up, this is an application based decision. Having the request(s) and repl(ies) persisted generally does not make sense. Since messages are "forever" logged, any subscriber starting at a point in the log could re-process the request, and what one would do with the persisted replies?

You mentioned the inboxes: these would become channels that would accumulate in the server and never be removed. Inboxes being unique and potentially not known from other applications, it would even be difficult to read back from those channels.

Finally, note that the streaming API gives you access to the internal NATS connection that it uses (for instance, Go: conn.NatsConn()). You can always use that and do request/reply if you have situations where you need both streaming and regular NATS.

(*) There is limits that can be set globally or per-channel that would cause old messages to be discarded. See a given message log as a ring buffer.
