### ISSUE TITLE
Issue with Subscriptions delivery

### ISSUE THREAD

**Issue by sachinwalia2k8** [nats-io/go-nats-streaming#146]
In my application I've a client that is publishing to a queue group as per following code.

`NatsConn.Publish("NotificationQueue", msgByte)
`
NatsConn -- global connection to Nats Streaming.

Receiver is initialized during bootstrap with function like this:

```
func InitSubscribers() {
	_, err := NatsConn.QueueSubscribe("NotificationQueue", "NotificationQueue", NotificationListener, stan.DurableName("DurableStore"))
}
```

The issue I am facing is that subscription delivery to listeners is not working and I am seeing following errors

`[DBG] STREAM: [Client:] Redelivering on ack expiration, subject=NotificationQueue, inbox=_INBOX.YOWGP5dxClqIzeZ4uNhHn1`

as well as

```
[DBG] STREAM: [Client:service001] Timed out on heartbeats
[DBG] STREAM: [Client:service001] Closed (Inbox=_INBOX.Uz0R99NZTSe467Ox6XIJTw)
```

Just wanted to check if there is some configuration that I may be missing.

**Comment by kozlovic** [comment]
By not working, what do you mean? Is the subscription not receiving any message at all? Which NATS Streaming server version are your running?

From log above, it looks like the application may be unreachable, or another usual suspect is that the application exited without closing the connection (NatsConn.Close()). Since Streaming clients are not directly connected to the Streaming server, the server uses heartbeats to decide if a client is closed. Until it decide it is so and removes it, it will attempt to redeliver unacknowledged messages to its subscriptions (it will actually stopped when detecting the first missed hb).

**Comment by kozlovic** [comment]
Any update on this?

**Comment by sachinwalia2k8** [comment]
I haven't been able to replicate this recently. Will create another issue if I am able to replicate it again.
