### ISSUE TITLE
How to send sync request just like gnatsd & go-nats library?

### ISSUE THREAD

**Issue by rafw** [nats-io/go-nats-streaming#155]
reply register OK:
`sub, err := conn.Subscribe("mysubj", func(m *stan.Msg) {
		...
		conn.Publish(m.Reply, "response")
	})
`

request returns error "nats: timeout".:
`
_, err := conn.NatsConn().Request("mysubj", "request data", time.Second * 5)
`

**Comment by kozlovic** [comment]
NATS and NATS Streaming cannot communicate with each other. NATS Streaming uses a specific namespace so that even when you use Streaming to subscribe on "foo", the subject is actually something different.

So although you have access to low-level NATS connection from streaming, when you do the request here, it goes to NATS `mysubj` subject, but NATS Streaming subscription is not on that subject.

**Comment by kozlovic** [comment]
Closing for now. I would also recommend that you have a look at [this](https://github.com/nats-io/nats-streaming-server#concepts) to get a better understanding at the relation between NATS and NATS Streaming. Thanks!
