### ISSUE TITLE
NATS Streaming Client left in inconsistent state when recovering from failure

### ISSUE THREAD

**Issue by bennettaur** [nats-io/go-nats-streaming#157]
I'm not sure if this is the intended behaviour but when I was running a setup of a producer, a nats-streaming-server (w/ Memory Store), and a consumer, and if the nats-streaming-server was restarted (in my case restarting the container), both my consumer and producer would reconnect (to NATS at least), however since I was using a memory store it would have no information about their previous subscriptions (as expected). It appeared though NATS allowed the consumer to create subscriptions (as listed in /connz) but NATS streaming server didn't seem to have any info on the clients (no clients, or channels), although everything still seemed like it was still connected. The client doesn't attempt to recreate the subscription and has no method of checking whether there is an issue.

Using a persistent Store fixes the issue however if recovering from the File Store fails for whatever reason, my consumers either need to detect and handle the case where NATS streaming has "forgotten" about them, or be manually reconnected.

**Comment by kozlovic** [comment]
What you observed is expected, and I feel that you understand that. The MemoryStore does not have persistence, so on restart it won't have any knowledge of current clients, subscriptions, channels, messages.

As you saw, the low level NATS subscriptions may be recreated, but that's not enough. Streaming server communicates with its clients through inboxes. For instance a subscription has a specific inbox that the server is sending messages to. That inbox is normally persisted in the subscription state in storage. Again, since there is no persistence, the server would not be able to send to that subscription.

Using the FileStore is required for resuming any work should the server fail. After a restart, apps actually reconnect to the NATS Server, but there is no direct connection to the streaming server. The server would start delivering messages to known inboxes. If server does not get ack back, it redeliver messages. From pub perspective, if a published message is not ack'ed, the publisher will be notified.
