### ISSUE TITLE
Connect function doesn't support tls certs

### ISSUE THREAD

**Issue by lynic** [nats-io/go-nats-streaming#173]
Using this library I can not specify clients certs for connect() function.

**Comment by kozlovic** [comment]
You need to create a NATS connection first and configure TLS as described [here](https://github.com/nats-io/go-nats#tls).
Once you have the NATS connection, pass it to `stan.Connect()` with the option `stan.NatsConn()`.
Note that since the streaming library then does not own the connection, you should close the NATS connection after closing the streaming connection.

**Comment by koliyo** [comment]
Please add this useful comment to the main README.md

**Comment by kozlovic** [comment]
@koliyo Can you have a look at PR #211 and see if that helps? Thanks.

**Comment by koliyo** [comment]
Yup, that was what I needed! 👍
