### ISSUE TITLE
document the error handling strategy this library is designed for

### ISSUE THREAD

**Issue by ripienaar** [nats-io/go-nats-streaming#176]
Coming from the `go-nats` library using this one can be a bit of a surprise.

It appears to me that if publish or ack ever fail you have to consider the connection stale and you have to close and recreate it and resubscribe.  There does not appear to be much by way of transparent reconnect handling here.

If you do not do this then long lived clients enter a state of being unusable as due to the heartbeats a server may have closed your connection - but due to the lack of reconnect handling here you now have a invalid session.

So publish/ack fails, you have to close and reconnect - thats the conclusion I came to while testing this.  

Additionally I cannot come up with any viable error handling strategy for a client that just consume messages from a stream in the face of long connection errors. They can get stuck in a state where no messages are ever received again after the network link recovers

It's also worth noting that during reconnects one can get a number of duplicate messages, for example given a stan connection with `stan.MaxPubAcksInflight(1)` and a subscription with `stan.MaxInflight(1)` during certain kinds of outage I still see the exact same message being sent to me 2, 3 or 4 times - even after on the first resend it was ACK'd - depending on duration of the outage and its nature (if its asymmetric in nature for eg.) perhaps due to the TCP buffers? That does not seem to honor the contract of not getting ACKd messages again.

I've even seen widely out of order deliveries at times on a client as above and with 1 workers not in a queue group, though failing to make a simple reproduction of that.

So in general I think it would be handy if you could document the strategies for error handling one should employ when using this library and some details about what kind of behaviour we can expect during outages wrt duplicates etc

**Comment by kozlovic** [comment]
Note about ack. If you talk about subscription ack, the contract is at-least-once, so it is possible that you receive the same message again (acks can always be missed by the server, etc..).

Ordering of redeliveries is not guaranteed, especially when it comes to queues and if you have multiple members. Even with single member, the redelivery is based on the AckWait and timestamp of each message. A message is probably not going to be redelivered until after that time elapses. If server is restarted though, and the original timestamp of the message is lower than current time + ackWait, it will be redelivered right away.

There is no good strategy due to the issues that you have opened before this one. A publish ack error (or timeout) is not necessarily indicative that the connection is lost for good. For instance, in the case of clustering where a leader goes down, and before a follower becomes the leader, the messages in-flight would get a timeout, but after the new leader is elected, new messages would continue to be accepted without the need for a teardown and recreation of the connection.

**Comment by ripienaar** [comment]
@kozlovic hmm, yes, but as I understood from earlier discussions on slack if I configure it to only send me 1 message without acks being processed and only allowing 1 ack in flight and not a queue (even a queue with just 1 subscriber)....then it should surely not be sending me any new stuff until the ack for message `n` was successfully processed, otherwise just keep sending `n`.

When we first spoke at length about ordering it appeared to me that this would ensure ordering is predictable and that even during the redelivery situation it would simply keep attempting to redeliver that one and never send me other messages until that one got acked.  Logically it seems possible for me that with only 1 in progress message, 1 in progress ack and 1 message buffer allowed that I should keep getting the same message over and over.
 
Further if I ack message `n` and it got it, why am I getting `n` again? I think this is due to the TCP buffer and the server retrying publishing because it does not know I am dead and I did not ack it...as you say.  In which case I can easily detect that and deal with it was it not for the out of ordering.

Regardless this ticket isn't really about ordering but more about the approach in general.  From this ticket and the other 2 - there is no possible way at present to run a streaming client that has an expectation of being long lived and with a unknown message rate.  You simply have no idea it stopped working.  I hope I am wrong, but in general the discovery process for how to handle ack and publish failures with this library is very painful :)

**Comment by kozlovic** [comment]
> t's also worth noting that during reconnects one can get a number of duplicate messages, for example given a stan connection with stan.MaxPubAcksInflight(1) and a subscription with stan.MaxInflight(1) during certain kinds of outage I still see the exact same message being sent to me 2, 3 or 4 times - even after on the first resend it was ACK'd - depending on duration of the outage and its nature (if its asymmetric in nature for eg.) perhaps due to the TCP buffers?

Say the server gets disconnected from NATS, as you know the streaming server is a NATS client, so any message that it publishes while the NATS Server is down would be buffered in the NATS client library. On reconnect, those published messages are flushed. So it is indeed possible that the server would resend the same non-ack'ed message multiple times if the disconnect lasted longer than an AckWait interval.

**Comment by ripienaar** [comment]
oh yeah of course the NATS buffer, obvious, ok.  Still, out of ordering issues there is weird to me.

**Comment by kozlovic** [comment]
I was thinking more about it, here is my thinking:

- Relying on NATS connection handlers is not sufficient: you could have the client connected to a NATS Server and never experience disconnect and yet be separated from the NATS Streaming Server if the later was connected to a different NATS Server that belongs to the same NATS cluster.
- We could certainly set the MaxReconnects to -1 for the NATS connection created by the library.
- Acting on server pings may not be good enough. Also, client would not know the interval/timeout so would need to have server sending those on connect. But a restart of the server with different values or failover to another server with different values would be problematic.

Based on the above, here is what I propose:

- Allow to specify a connection closed handler that accepts the failed connection object and a reason as to why the connection is closed.
- Introduce new client options: ping interval/timeout/failed count similar to the server options. The library will send pings at regular interval with information identifying this client (clientID an internal unique ID (part of the heart beat inbox that the server knows about). If no response is received in the given timeout, increment the number of failed count. If that reaches the specified max, or if the nats connection is reported closed (for sure no more connection to NATS), close the streaming connection and if the above callback has been set, invoke.
- Add the unique ID to published messages. This would allow the server to detect the situation where the client was "separated" from the server and another client with same client ID took its place. When the former client has now resumed communication with the server, and before the pinger detects that the connection is no longer valid (same client ID but different unique ID), the server would reject the published message because the client ID+unique ID would not match.

When the closed connection handler is invoked, the user would need to re-create connection and subscriptions if desired. Doing that automatically proves difficult because the original start sequence would cause server to resend a bunch of messages that may have been processed already. For regular subs, library could maintain floor and keep track of unack messages so that acked messages resent are ignored, but that would be more difficult with queue groups since there is gaps in message sequences. If all members on the group (but not from the same connection) were to be "disconnected", the first connection to recreate the member with its view of the floor would cause other members that recreate to possibly ignore unacknowledged messages that were below this floor.

Even the proposed changes will require changes in the server and client. For instance the pinger can be activated only if the server tells the client that it listen for those.

How does the above sound to you? Any feedback appreciated.

**Comment by kozlovic** [comment]
Thanks for the feedback.. here are some comments:

> It's sad we can't recreate the connection and subs magically but you're right its not possible for non durable subs (i really think those have very limited use anyway for STAN but thats just me apparently)

The one that I really have a problem with, actually, is the non-durable queue group. The durable (queues or not) are easy, since the start position is ignored when the group is maintained in the server. For the non durable plain sub, it would be somewhat easy to keep the floor and ack'ed messages (when manual ack mode) to recreate the sub. But for non-durable queue sub, imaging the following scenario: 2 apps on the same group. First receives messages 1, 3, 5, 7 and does not ack 5, so the floor would be remembered as 5, with ack'ed 7 (so the library can drop that message if it was resent). The second app received 2, 4, 6, 8 and did not ack message 2, so its floor would be 2 and ack'ed 4, 6 and 8. Finally, supposed those 2 connections are "separated" long enough from the server that the server drops those 2 connections and each app detects and tries to recreate. If the first app happens to be the one recreating the group, it would create with a start sequence of 5, which means that the second app recreating the qsub with start sequence of 2, that one would be ignored (since the group has been recreated). Server would start sending only at seq 5+, which means message 2 would never be redelivered although the app wanted it to be. 

> When you say add options for heartbeating, I assume you also mean enable by default with good default settings and not opt-in

We could do that indeed, although keep in mind that this would be enabled only when a client connects to a server supporting client heartbeats. Which also means that there is a possibility that a client initially connects to a server that does support, but then the server is stopped and restarted with an older version that does not. The client would still send those heartbeats for which it would not get a response and assume that the connection is lost, and close it.

> I think it's implied but worth stating it's essential both sides do heartbeats and either side can decide to terminate a connection.

Yes, as you know, server is already sending HBs to clients. What would be added is client-to-server.

> I also like how stomp does it https://stomp.github.io/stomp-specification-1.1.html#Heart-beating where both sides can declare their minimum viable heartbeat frequency and the highest of the possible frequencies are chosen, this works well with different languages, environments etc

Will look into that. We do have a notion of max failed HBs that is not specified in that link. They basically expect to receive an HB in the interval specified and if otherwise can consider the connection lost, although they mentioned that it must be tolerant of some inaccuracies. We use the number of failed pings instead.

**Comment by ripienaar** [comment]
> The one that I really have a problem with, actually, is the non-durable queue group. The durable (queues or not) are easy, since the start position is ignored when the group is maintained in the server. 

Indeed yeah I get the problem, thanks for the detail though!

> We could do that indeed, although keep in mind that this would be enabled only when a client connects to a server supporting client heartbeats. Which also means that there is a possibility that a client initially connects to a server that does support, but then the server is stopped and restarted with an older version that does not. The client would still send those heartbeats for which it would not get a response and assume that the connection is lost, and close it.

but then it would reconnect and renegotiate the things and recover.  It's not a bad story for a major server upgrade/downgrade really where protocol changes are involved and one might expect or at the very least not be too surprised about.

> Will look into that. We do have a notion of max failed HBs that is not specified in that link. They basically expect to receive an HB in the interval specified and if otherwise can consider the connection lost, although they mentioned that it must be tolerant of some inaccuracies. We use the number of failed pings instead.

STOMP is not known for being a very clear specification lol, the spirit is there and I think your `n` missed messages per interval is a better pattern than they have.  Together being able to negotiate the interval and the n misses will work really well

**Comment by derekcollison** [comment]
Good thought on negotiated HBs. We should create a separate issue for this, and also look into client and server KeepAlive settings for underlying socket. Only question I have is whether or not the server would always accept a very large interval from a client since it will hold resources for that client.
