### ISSUE TITLE
Unclear what Ack really does

### ISSUE THREAD

**Issue by JohnnyQQQQ** [nats-io/go-nats-streaming#177]
I tried to play around with the nats-streaming-server today, great project. I have one question regarding the manual ack mode. From my understanding, the publish method wouldn't return till an ack is given.

Running the following code

```golang
package main

import (
	"github.com/nats-io/go-nats-streaming"
	"log"
	"time"
	"fmt"
)

func main() {
	conn, err := stan.Connect("test-cluster", "client1",
		stan.NatsURL(stan.DefaultNatsURL), stan.PubAckWait(time.Second * 12))
	if err != nil {
		log.Println(err)
	}
	conn.Subscribe("test.topic", func(msg *stan.Msg) {
		log.Println("Recieved Message, waiting 10 seconds till Ack()")
		log.Println(string(msg.Data))
		time.Sleep(time.Second * 10)
		msg.Ack()
		log.Println("Done!")
	}, stan.SetManualAckMode())
	fmt.Println("Sending Message")
	err = conn.Publish("test.topic", []byte("My Message")) // I would expect a 10 seconds delay here
	if err != nil {
		log.Println(err)
	}
	fmt.Println("Returned from sending Message")
	time.Sleep(time.Second * 3000)

}
```

I would expect a 10 second break at `err = conn.Publish(..` 

Am I missing something? Is there a documentation where the concepts are explained? I did only find the brief introduction under https://nats.io/documentation/streaming/nats-streaming-intro/

Does `Publish` only wait for the ack from the server and not the ack from the client (this is what I could read between the lines in the docs)? 

If so I have a follow-up question: when I stop the subscriber without acknowledging the message, why does the server not re-send the message on connection? I there an option to get all messages that where not acknowledged? `StartWithLastReceived` and `DeliverAllAvailable` worked as intended though but do not solve the problem or are a bit overkill.

Cheers!

**Comment by kozlovic** [comment]
There are 2 types of Acks. One is the server sending an ACK to your publisher. It says that the server has received and persisted it (on disk or memory that depends on the store type you use when starting the server). It is unrelated to the consumer. The consumer ACK is sent by the application to the server to let it know that it should not try to redeliver that message.
(see that issue I just answered to today: https://github.com/nats-io/nats-streaming-server/issues/554)

When you create your subscription, you can specify `AckWait()` which instructs the server to redeliver a message if it did not receive an Ack by the application (explicit or implicit if not using `SetManualAckMode()`). In your example, since you don't specify `AckWait()`, the default is 30 seconds, so server would not attempt to redeliver since you ack it within 10 seconds.

Before answering your followup question, again, check the link to previous answer and this [link](https://github.com/nats-io/nats-streaming-server#message-log). As explained there, the server stores messages regardless of interest. In your example, when the subscription exit, and even if it was exiting before acknowledging a message the message would not be redelivered because: 1, the subscription is is gone, so where the server would redeliver the message to? 2, the subscription is not durable, so there is no need to maintain the state for that subscription.
With a durable subscription, closing a durable with unacknowledged messages would cause the server to redeliver those when restarting the durable.
And keep in mind that you always have the possibility to create a new subscription at any point in the stream, since messages are not removed simply because they have been previously consumed.

**Comment by JohnnyQQQQ** [comment]
Thanks for the clarification @kozlovic helped me big time to get my head around the details of the implementation.
