### ISSUE TITLE
Unable to connect to nats streaming server - Timeout issue

### ISSUE THREAD

**Issue by subbu05** [nats-io/go-nats-streaming#178]
I started streaming server  one one host 10.0.0.5
./nats-streaming-server  -mc 0  -msu 0

On another host i started running client
stan-sub -s nats://10.0.0.6:4222 -id 1 1 

I am getting following error
Can't connect: stan: connect request timeout.
Make sure a NATS Streaming Server is running at: nats://10.0.0.6:4222

But from the client box if I do **telnet 10.0.0.6 4222**
I am able to get response.

**Comment by kozlovic** [comment]
The way you start the streaming server, it means it embeds the NATS server and listens by default to port 4222 (since you did not override that). If you start nats streaming on host 10.0.0.5, then you should point your client to that host, not 10.0.0.6.

The fact that telnet on `.6` port 4222 works may mean that you have something (maybe NATS) running on that host/port, but that's not the streaming server. So please run `stan-sub -s nats://10.0.0.5:4222` and re-open if you still have an issue.
