### ISSUE TITLE
Managing ClientId for multiple instances

### ISSUE THREAD

**Issue by anjmao** [nats-io/go-nats-streaming#208]
Hi, I'm trying to figure out how should I manage client id if I have my backend service running on multiple kubernetes pods. (My backend is a small monolith, it contains gRPC endpoints and NATS Streaming client)

My use case is that I have QueueSubscribe (only one of the instances can process published message) and it should be durable. (If I deploy new version of my service I should get not processed messages).
```go
natsConn.QueueSubscribe(
	"SubjectName",
	"group1",
	func(m *stan.Msg) {},
	stan.SetManualAckMode(),
	stan.DurableName("my-durable")
)
```

My backend service running on docker in kubernetes
Instance 1
```go
stan.Connect("test-cluster", "my-service-instance-1")
```
Instance 2
```go
stan.Connect("test-cluster", "my-service-instance-2")
```
The problem is in clientId, since each stan connection should have unique client id I need to somehow persist client ids. Is where is any good practice for that or should I just store client ids in some database and load on start (this adds some complexity). Another solution I was thinking of is to move subscribers to separate microservice and run on one instance only.

**Comment by kozlovic** [comment]
The client ID need to be unique, but does not have to be the same after a restart for queue subscriptions (this is not true for non-queue durable subscriptions). So you could use a generated unique ID for those services.

I am sure that you've checked the README in this repo, and I would recommend also looking at the one in the server, specifically the Queue group since this is what you are using: https://github.com/nats-io/nats-streaming-server#queue-group

**Comment by anjmao** [comment]
@kozlovic Thanks a lot, yes I was testing with non queue subscribers, it works with QueueSubscribe 👍

**Comment by mehran-prs** [comment]
How about durable queue subscriptions? to remove it, each client needs to unsubscribe, but after a restart, we don't have client-ids.

**Comment by mehran-prs** [comment]
Thanks a lot. I misunderstood the docs, <del>I thought we need to call Unsubscribe() with the same client id.<del>
