### ISSUE TITLE
What is stan client best practices?

### ISSUE THREAD

**Issue by leenux** [nats-io/go-nats-streaming#217]
Is a singleton client/connect necessary?
Is the client a connection pool?
Does requiring new connections before each publish affect performance?

**Comment by ripienaar** [comment]
One connection can perform a lot of work and reconnecting is expensive. You want to keep a long running connection and if you have many workers you might have one per worker

**Comment by kozlovic** [comment]
As @ripienaar mentioned, it is best practice to keep the connection opened. Clearly it would be super inefficient to create a connection for publishing a single message. This is true in general, but especially with Streaming since creating a connection and closing it are req/replies and server persists state for each of these events.
