### ISSUE TITLE
 stan: clientID already registered.

### ISSUE THREAD

**Issue by cpani** [nats-io/go-nats-streaming#220]
sc, err := stan.Connect("test_cluster", "cliend-id", stan.NatsURL("nats://ipaddr:4222"))

gives me following error:
stan: clientID already registered.

Need some help to understand how to avoid this error.

**Comment by ripienaar** [comment]
Each connection needs a unique client id, your `cliend-id` is already in use

**Comment by cpani** [comment]
@ripienaar . Yes I can understand that from the error message. I am looking for api which will not give me the above error. If the clientID already exist , how to use the existing one. 
If I am running the server, client in different containers, every time I restart my client will give me this error?

**Comment by ripienaar** [comment]
You need to close your connections when you exit then the problem goes away - or generate unique IDs the old ones will expire after a while.

**Comment by cpani** [comment]
Is there any way I can get existing connection for already registered clientID?

**Comment by kozlovic** [comment]
When you create a connection, you need to provide a clientID. This has to be unique in that server accepts only 1 running connection with same client ID. If connection is closed, then a new connection can be created with that same client ID. Client ID are necessary for durable subscriptions since the combination of the two creates the actual durable name.

More on client connections can be found [here](https://github.com/nats-io/nats-streaming-server#concepts), and more specifically [here](https://github.com/nats-io/nats-streaming-server#client-connections).
