### ISSUE TITLE
How to use stan.Connect() in go routines?

### ISSUE THREAD

**Issue by cpani** [nats-io/go-nats-streaming#221]
Hello,

I am creating a connection and passing that connection to another go routine.
I am using the connection to publish message in that go routine. But I am getting error stan: connection closed.
```
func test1(){
sc,err := stan.Connect("test-cluster", "clientId", stan.NatsURL("nats://0.0.0.0:4222"))
go testGoRoutine(sc)
}

func testGoRoutine(sc stan.Conn){
err := sc.Publish("subj", payloadBytes)
}

```

I am getting the error stan: connection closed.

**Comment by derekcollison** [comment]
Can you check what *err* is when you try to connect? Is it non-nil?

**Comment by cpani** [comment]
I am not getting error while connecting. But when I try to Publish using the connection passed to another goroutine , I am getting the error "stan: connection closed."

**Comment by kozlovic** [comment]
Can you provide your entire test case? It could be that the connection has been closed before the go routine has a chance to execute.

**Comment by cpani** [comment]
@kozlovic:

There is little modification in the code :
func test1(){
for i:=0; i<5; i++{
sc,err := stan.Connect("test-cluster", "clientId”+i, stan.NatsURL("nats://0.0.0.0:4222"))
go testGoRoutine(sc)
}
}

func testGoRoutine(sc stan.Conn){
err := sc.Publish("subj", payloadBytes)
}


I am invoking goroutine inside a loop. Creating a connection for each loop. 

Issues I am facing :
1. If I create one connection outside the loop and pass that connection to goroutine , then I am getting error: “ClinetID already registered “
2. If I create a new connection for each go routine invocation ( I.e inside the loop), I am getting the error : connecting closed during publishing the message.

Hope I was able explain the issue.

**Comment by cpani** [comment]
@kozlovic One more observation , when I pass the Connection to a normal function and publish the message from that function, it works fine. But when I pass the connection to a go routine and publish the message from there, I get connection closed error.

**Comment by kozlovic** [comment]
I asked you to provide a complete runnable test case in order to help you. If I were to copy do the same that you do above, I don't have a problem. There are "issues" with what you are doing, but would not explain the connection closed.

You need to read https://github.com/nats-io/nats-streaming-server#relation-to-nats and https://github.com/nats-io/nats-streaming-server#client-connections to understand more about the connections semantics. For instance, in your example you don't close the connections, so if you were to repeat the test without recycling the server (with mem store), then older connections would be replaced by new ones assuming that the original program that created the connections has stopped running. 

Again, please provide a complete, runnable, test case that demonstrate the problem and describe exactly how you are running the test (how many instances if more than one), if you restart the server, etc.. any steps required to reproduce the problem.
Thanks!

**Comment by kozlovic** [comment]
Closing for now.. Will re-open if you provide more information. Thanks!
