### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by JensRantil** [nats-io/go-nats-streaming#232]
I am reading through the [godoc](https://godoc.org/github.com/nats-io/go-nats-streaming) and notice that there are lots of interface methods and struct fields that are undocumented. Examples:

 * https://godoc.org/github.com/nats-io/go-nats-streaming#Options doesn't document its fields.
 * https://godoc.org/github.com/nats-io/go-nats-streaming#Subscription doesn't document most of its methods. For example `MaxPending() (int, int, error)` doesn't say anything about what the returned `int`s are.

Going forward, I propose adding a linter that requires all public entities to be documented which I think should be considered best-practise for a well-written library.

**Comment by kozlovic** [comment]
@JensRantil Thank you for the feedback. I have attempted to add some documentation, but I am sure it is far from complete. A note about some of the functions in `Subscription`. It is unfortunate that they were added. These are relative to the low level NATS subscription that is used internally by the library. They were added because an early adopter of the library submitted a PR to add them (https://github.com/nats-io/go-nats-streaming/pull/116). In hindsight, we should probably have not done so since it can be very confusing.
