### ISSUE TITLE
Is There A Way To Send A Message Of Size > 1MB using nats-streaming

### ISSUE THREAD

**Issue by Mr7Sir** [nats-io/go-nats-streaming#237]
I am trying to send a file using the nats messaging service. The size of the files may vary. Is there a way to send more than 1MB of data in a message body, or possible break and join the message body?

**Comment by derekcollison** [comment]
The NATS server allows you to configure the max payload. In general we do not suggest using a large payload size. You can chunk a larger payload into smaller pieces. There are several ways to do achieve this.

**Comment by Mr7Sir** [comment]
> The NATS server allows you to configure the max payload. In general we do not suggest using a large payload size. You can chunk a larger payload into smaller pieces. There are several ways to do achieve this.

Can you please expand as to why a larger payload size is not recommended even though nats-streaming server provides such a feature?

**Comment by derekcollison** [comment]
NATS is a messaging system. It understands message boundaries and routes messages to subscribers. Given this it needs to hold the message to deliver it, and therefore it is recommended to not have very large messages. Tons of smaller ones is fine since the system re-uses the memory and can do other things in between messages, etc.
