### ISSUE TITLE
Understanding the "stan: duplicate durable registration" error

### ISSUE THREAD

**Issue by mennanov** [nats-io/go-nats-streaming#241]
I'm getting the `stan: duplicate durable registration` error when calling the `Subscribe()` method in my app integration tests.
Could not find an explanation in the docs, looking at the source at https://github.com/nats-io/nats-streaming-server/blob/master/server/server.go#L4438 did not make it clear to me either. 
Thus, asking for help here.

What behavior/misconfiguration may cause this error?

**Comment by kozlovic** [comment]
A durable (non queue) subscription for a given channel is formed with the client ID and durable name. Since a client ID needs to be unique, you can't have 2 durable with the same client ID + durable name.
From the same connection (clientID), you cannot create 2 durable subscriptions with the same name for a given channel.
If you attempt to do so, the server will fail the second Subscribe() request with this error.

**Comment by mennanov** [comment]
It clarifies everything, thanks!
