### ISSUE TITLE
Exposing underlying NATS conn

### ISSUE THREAD

**Issue by tylertreat-wf** [nats-io/go-nats-streaming#67]
It would be nice if the STAN conn exposed a way to get the wrapped NATS conn. For example, if I have a STAN conn, I want to check if it's connected to NATS. Either STAN would need to have a `Status()` method which calls through to the NATS conn or we just allow you to get the NATS conn itself.

I see the potential dangers with this (e.g. closing the underlying NATS conn would be quite problematic), but if you are passing in your own NATS conn, this is already a possibility. And if STAN is creating the NATS conn for you, there's currently no way to check the NATS status.

**Comment by mcqueary** [comment]
This is an issue we have discussed internally. I don't remember all the salient issues, but I am sure @kozlovic or @ColinSullivan1 can refresh our memories. Think we were concerned about allowing manipulation of NATS options and callbacks, but I agree that at least `Status()` should be exposed.

**Comment by ColinSullivan1** [comment]
@tylertreat @kozlovic @mcqueary  I agree that Status() should be exposed.  One can still create a NATS streaming connection passing a plain NATS connection - required today to setup TLS.  IMO, since we do that, there isn't much more danger in providing, as "advanced" usage, an API that returns the underlying NATS connection.  We'd need to thoroughly document the dangers though...

**Comment by kozlovic** [comment]
Resolved with #86
